# Generated by Django 3.2 on 2021-08-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('memory', models.CharField(max_length=120)),
                ('os', models.CharField(max_length=120)),
                ('specs', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
